server:
  port: 9355
  servlet:
    session:
      tracking-modes: cookie

sa-token:
  token-name: satoken
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yiyou
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 2048MB

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  http:
    multipart:
      location: /data/upload_tmp
logging:
  level:
    com.work: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

identify:
  url: https://idcert.market.alicloudapi.com/idcard?idCard=%s&name=%s
  appKey: 204262225
  appSecret: GhmbQgVwjKWpErVJj0Lenz6qQymuxNgV
  appCode: ba6bb17924cd48a1ae6054bebfa5ae6b