server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yiyou?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username:
    password: 

  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
logging:
  level:
    com.work: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

identify:
  url: https://idcert.market.alicloudapi.com/idcard?idCard=%s&name=%s
  appKey: 204262225
  appSecret: GhmbQgVwjKWpErVJj0Lenz6qQymuxNgV
  appCode: ba6bb17924cd48a1ae6054bebfa5ae6b