server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yiyou
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.example: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml